name: Build and test on Linux
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-linux"
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake and build
      run: ./scripts/create_release.sh withTests
    - name: Run tests
      run: ./scripts/run_tests.sh Release