name: Build and test on Windows
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-windows"
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake and build
      run: ./scripts/windows/create_release.ps1 withTests
    - name: Run tests
      run: ./scripts/windows/run_tests.ps1 Release